### ISSUE TITLE
Virtualbox 6.1.3 fails to boot Catalina 10.15.2

### ISSUE THREAD

**Issue by adamwolf** [bacongravy/macinbox#47] opened 2020-01-29 20:50 UTC
Hi folks!  Thanks for this amazing tool!

I am running macOS 10.15.2, and have installed macinbox, Virtualbox and Vagrant.

I ran `sudo macinbox --box-format virtualbox`, and it appears to have succeeded. I then created a tmp directory, went into it, and `vagrant init macinbox`, and virtualbox starts up.  I eventually get to a EFI text screen that ends in Found fs2:\System\Library\CoreServices\boot.efi, loading...

I have left it there overnight and it doesn't seem to go anywhere.  Any thoughts?

Thanks!

**Comment by bacongravy** [comment] 2020-01-29 21:49
Hi @adamwolf, thank you for writing this up. This looks similar to the issue reported here: https://github.com/AlexanderWillner/runMacOSinVirtualBox/issues/95

...which may in fact be in a bug in Virtualbox:
https://www.virtualbox.org/ticket/19188

The stated workaround, of using a previous OS version's boot.efi, is not really viable for `macinbox`.  I think best path forward right now if you want to use `macinbox` is to either use Catalina 10.15.1 instead of 10.15.2, or Parallels instead of Virtualbox.

**Comment by adamwolf** [comment] 2020-01-29 21:55
Wow!  What a fast response!

Is there a way for me to build a 10.15.1 base while being on 10.15.2?

**Comment by Korop** [comment] 2020-01-29 21:59
The same issue with 10.15.3 just has checked the macinbox with it.

**Comment by bacongravy** [comment] 2020-01-29 23:50
Yes, you can build a 10.15.1 box while being on 10.15.2.  You just need a copy of the 10.15.1 installer someplace.  You can use the `--installer` or `--installer-dmg` options to override which installer is used as the source.  You might be able to use [installinstallmacos.py](https://github.com/munki/macadmin-scripts/blob/master/installinstallmacos.py) to download a 10.15.1 installer if you don't currently have one.

**Comment by adamwolf** [comment] 2020-01-30 01:22
Thanks! I can't find any way, from softwareupdate --fetch-full-installer to installinstallmacos.py or even just google, to download 10.15.1 or 10.15.0 anymore.

This is going to be trickier than I thought.

**Comment by jaanus** [comment] 2020-01-30 07:18
@bacongravy can you confirm that this is specific to Virtualbox, and that you have seen 10.15.2 working in Parallels?

**Comment by bacongravy** [comment] 2020-01-30 20:02
@jaanus I have not personally confirmed that Parallels or VMware Fusion work with 10.15.2 or 10.15.3, but I also have not heard any reports about those failing, either.

I should be able to confirm that this issue does not impact Parallels later today.

**Comment by bacongravy** [comment] 2020-01-30 20:08
@adamwolf If you're willing to use a box that someone else built, check out this project: https://app.vagrantup.com/ramsey/boxes/macos-catalina

I haven't tried myself, but from reading the documentation it looks like you could get a Virtualbox-format box with macOS 10.15.1 from Vagrant Cloud.  I can't vouch for the contents of the box, though. Use at your own risk!

**Comment by adamwolf** [comment] 2020-01-30 20:42
I have been able to find a 10.15 install DMG from a university tech support
FTP.  *sob sob*

**Comment by bacongravy** [comment] 2020-01-31 01:43
I was able to use `macinbox` to generate a VMware Fusion box from the 10.15.3 installer and the box boots successfully.

**Comment by bacongravy** [comment] 2020-01-31 03:03
I was also able to use `macinbox` to generate a Parallels box from the 10.15.3 installer and the box boots successfully with Parallels Desktop 15.0.0.

HOWEVER, if I use Parallels Desktop 15.1.2 to create the box, then the created box fails to boot.  (15.1.2 can boot the box created by 15.0.0.)  It appears that the `prl_convert` tool is producing an unbootable hdd with version 15.1.2. This is an entirely unrelated issue that I will file separately.

**Comment by schrodincat** [comment] 2020-02-25 11:49
@bacongravy can confirm the box made with Parallels Desktop 15.1.2 doesn’t start

**Comment by DanielWright** [comment] 2020-02-25 18:31
The bug in VirtualBox appears to have been fixed in the 6.1.4 release. I'm able to run macOS 10.15.3 boxes without issue.

**Comment by bacongravy** [comment] 2020-02-25 19:23
@schrodincat The issue with Parallels Desktop issue have been filed as #49. Thanks for the confirmation.

Since the issue with VirtualBox has been fixed with the 6.1.4 release I am going to close this issue.

**Closed by bacongravy** 2020-02-25 19:23 UTC
