### ISSUE TITLE
Feature request: find out how to csrutil disable

### ISSUE THREAD

**Issue by egandro** [bacongravy/macinbox#32] opened 2019-02-15 00:34 UTC
--csr-disable would be so awesome

I only found this: https://www.imore.com/how-turn-system-integrity-protection-macos

But maybe there is a OSX'ish chroot?

**Comment by egandro** [comment] 2019-02-15 00:35
There is a jail equivalent:

http://galvanist.com/post/56925855686/chroot-jails-on-os-x

**Comment by egandro** [comment] 2019-02-15 00:44
Yes there is BSD chroot. So we might have a chance.

**Comment by bacongravy** [comment] 2019-02-15 03:50
Duplicate of #4.

**Closed by bacongravy** 2019-02-15 03:50 UTC
